"""Add RL Interactions table

Revision ID: add_rl_interactions
Revises: 5bf30a2add2a
Create Date: 2025-01-XX XX:XX:XX.XXXXXX

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'add_rl_interactions'
down_revision: Union[str, None] = '5bf30a2add2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rl_interactions',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('poi_id', sa.String(), nullable=False),
    sa.Column('reward', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rl_interactions_user_id'), 'rl_interactions', ['user_id'], unique=False)
    op.create_index(op.f('ix_rl_interactions_poi_id'), 'rl_interactions', ['poi_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rl_interactions_poi_id'), table_name='rl_interactions')
    op.drop_index(op.f('ix_rl_interactions_user_id'), table_name='rl_interactions')
    op.drop_table('rl_interactions')
    # ### end Alembic commands ###

